export const teamColors = {
	red_bull: '#0600EF',
	ferrari: 'red',
	alpine: '#0090FF',
	haas: '#FFFFFF',
	aston_martin: '#006F62',
	alphatauri: '#2B4562',
	mclaren: '#F88700',
	alfa: '#900000',
	williams: '#005AFF',
	mercedes: '#00D2BE',
};

export const driverColors = {
	max_verstappen: '#0033cc',
	leclerc: 'red',
	perez: '#0033cc',
	russell: '#00D2BE',
	sainz: 'red',
	alonso: '#006F62',
	albon: '#005AFF',
	bottas: '#900000',
	gasly: '#0090FF',
	hulkenberg: '#FFFFFF',
	kevin_magnussen: '#FFFFFF',
	norris: '#F88700',
	ocon: '#0090FF',
	piastri: '#F88700',
	sargeant: '#005AFF',
	tsunoda: '#2B4562',
	de_vries: '#2B4562',
	zhou: '#900000',
	stroll: '#006F62',
	hamilton: '#00D2BE',
};

export const driverTeams = {
	max_verstappen: 'Red Bull',
	leclerc: 'Ferrari',
	perez: 'Red Bull',
	russell: 'Mercedes',
	sainz: 'Ferrari',
	alonso: 'Aston Martin',
	albon: 'Williams',
	bottos: 'Alfa Romeo',
	gasly: 'Alpine',
	hulkenberg: 'Haas',
	kevin_magnussen: 'Haas',
	norris: 'McLaren',
	ocon: 'Alpine',
	piastri: 'McLaren',
	sargeant: 'Williams',
	tsunoda: 'Alpha Tauri',
	de_vries: 'Alpha Tauri',
	zhou: 'Alfa Romeo',
	stroll: 'Aston Martin',
	hamilton: 'Mercedes',
};
